repos:
  - repo: local
    hooks:
    - id: jira-ticket
      name: check for jira ticket
      language: pygrep
      entry: '\A(?![A-Z]+-[0-9]+)'
      args: [--multiline]
      stages: [commit-msg]