version: "3.3"

services:
  test:
    build: 
      context: .
      dockerfile: test/unit-test/Dockerfile
    container_name: cloudin-test
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  manual-test:
    build: 
      context: .
      dockerfile: test/integration-test/Dockerfile
    container_name: cloudin-test
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://backend:api5sem@ec2-54-91-130-106.compute-1.amazonaws.com:3306/cloudin
