version: "3.3"

services:

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cloudin
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
