version: "3.3"

services:
  test:
    build: 
      context: .
      dockerfile: test/unit-test/Dockerfile
    container_name: cloudin-test
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  manual-test:
    build: 
      context: .
      dockerfile: test/integration-test/Dockerfile
    container_name: cloudin-test
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  web:
    container_name: cloudin-backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 10050:100050
