apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudin-midall
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudin-midall
            port:
              number: {{ .Values.backend.ports.containerPort }}
