apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudin-midall
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudin-midall
            port:
              number: 5000
