apiVersion: v1
kind: Service
metadata:
  name: cloudin-midall
  labels:
    app: cloudin-midall
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.backend.ports.containerPort }}
    targetPort: {{ .Values.backend.ports.containerPort }}
    protocol: TCP
    name: http
  selector:
    app: cloudin-midall