name: Deploy to Azure AKS

on:
  push:
    branches:
      - dev 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get the latest Docker image tag
      id: get_last_tag
      run: |
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ secrets.DOCKER_USERNAME }}'", "password": "'${{ secrets.DOCKER_PASSWORD }}'"}' "https://hub.docker.com/v2/users/login/" | jq -r .token)
        LAST_TAG=$(curl -s -H "Authorization: JWT $TOKEN" -X GET "https://hub.docker.com/v2/repositories/dolphindatabase/midall-backend-api5/tags/?page_size=1" | jq -r '.results[0].name')
        echo "::set-output name=tag::$LAST_TAG"

    - name: Increment the Docker image tag
      id: increment_tag
      run: |
        LAST_TAG=${{ steps.get_last_tag.outputs.tag }}
        IFS='.' read -ra VERSION <<< "$LAST_TAG"
        MAJOR=${VERSION[0]}
        MINOR=${VERSION[1]}
        PATCH=${VERSION[2]}
        PATCH=$((PATCH + 1))
        NEW_TAG="$MAJOR.$MINOR.$PATCH"
        echo "::set-output name=tag::$NEW_TAG"

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE: dolphindatabase/midall-backend-api5
      run: |
        IMAGE_TAG=${{ steps.increment_tag.outputs.tag }}
        docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push $DOCKER_IMAGE:$IMAGE_TAG

    - name: Deploy Helm chart to AKS
      run: |
        az account set --subscription 16cbcfe3-5051-4f12-bebe-6919e9f04763
        az aks get-credentials --resource-group azure-cluster --name azure-cluster
        ls $GITHUB_WORKSPACE/teste/Cloudin-backend/
        cd $GITHUB_WORKSPACE/teste/Cloudin-backend/
        git pull
        cd ./cloudin-midall/
        helm package .
        helm upgrade cloudin ./cloudin-midall-1.0.0.tgz --namespace cloudin-cd --set backend.image.tag=$IMAGE
