name: Deploy to EC2
on:
  pull_request:
      branches: 
       - main
      types: [closed]
jobs:

  build-test:
    name: Build
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
    - name: Repository pull 
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
                  cd /home/ec2-user/Cloudin-backend
                  git pull
                  docker-compose build mysql
                  docker-compose build web
