name: Deploy to EC2
on:
  pull_request:
      branches: 
       - main
      types: [closed]
jobs:
  build:
    name: Build
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
                    cd /home/ec2-user/Cloudin-backend
                    git pull
                    ./../cleanContainer.sh
                    docker-compose build web
                    docker-compose run web
