name: Test
on:
  pull_request:
      branches: 
       - dev
      types: [closed]
jobs:
  Test:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker-compose build test
    - name: Run tests
      run: |
        docker-compose run --rm -e GOOGLE_TOKEN=${{ github.event.inputs.logLevel }} -e GOOGLE_FOLDER=${{ github.event.inputs.logLevel }} -e S3_TOKEN=${{ github.event.inputs.logLevel }} -e S3_FOLDER=${{ github.event.inputs.logLevel }} test 
