name: Test
on:
  push:
      branches:
        - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker-compose build test
    - name: Run tests
      run: |
        docker-compose run --rm test 
        docker exec -it test python -m pytest test/unit-test/test_google.py
